# Generated by Django 6.0.4 on 2026-04-24 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=100, unique=True, verbose_name='Артикул/SKU')),
                ('name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество на складе')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Закупочная стоимость')),
                ('delivery_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость доставки')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Себестоимость')),
                ('status', models.CharField(choices=[('in_stock', 'В наличии'), ('in_sale', 'В продаже'), ('sold', 'Продано')], default='in_stock', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='SaleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=100, verbose_name='Артикул/SKU')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('sale_type', models.CharField(choices=[('ozon', 'Продажа Ozon'), ('free', 'Свободная продажа')], max_length=20, verbose_name='Тип продажи')),
                ('income', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Доход (цена продажи)')),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Прибыль')),
                ('sale_date', models.DateField(auto_now_add=True, verbose_name='Дата продажи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='web.product', verbose_name='Связанный товар')),
            ],
            options={
                'verbose_name': 'Запись о продаже',
                'verbose_name_plural': 'Записи о продажах',
            },
        ),
    ]
