# Generated by Django 6.0.4 on 2026-04-30 16:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ozon_product_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Ozon product ID'),
        ),
        migrations.AddField(
            model_name='product',
            name='ozon_sku',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Ozon SKU'),
        ),
        migrations.AddField(
            model_name='salerecord',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Внешний ID'),
        ),
        migrations.AddField(
            model_name='salerecord',
            name='posting_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Ozon posting number'),
        ),
        migrations.AlterField(
            model_name='salerecord',
            name='sale_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата продажи'),
        ),
    ]
