# Generated by Django 6.0.4 on 2026-04-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_product_ozon_product_id_product_ozon_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ozon_status',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ozon status'),
        ),
        migrations.AddField(
            model_name='product',
            name='ozon_visibility',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ozon visibility'),
        ),
    ]
