# Generated by Codex on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_product_ozon_status_product_ozon_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerecord',
            name='accrual_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начисления'),
        ),
        migrations.AddField(
            model_name='salerecord',
            name='accrual_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Ozon accrual ID'),
        ),
    ]
