# Generated by Codex on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_salerecord_accrual_date_salerecord_accrual_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerecord',
            name='accrual_details',
            field=models.JSONField(blank=True, default=dict, verbose_name='Ozon accrual details'),
        ),
    ]
