# Generated by Codex on 2026-05-16

from django.db import migrations, models


def split_stock_statuses(apps, schema_editor):
    Product = apps.get_model('web', 'Product')
    for product in Product.objects.all():
        if product.status == 'in_sale':
            product.ozon_quantity = product.quantity
            product.quantity = 0
            product.status = 'in_stock_ozon'
            product.save(update_fields=['ozon_quantity', 'quantity', 'status'])
        elif product.status == 'in_stock':
            product.status = 'in_stock_warehouse'
            product.save(update_fields=['status'])


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_salerecord_accrual_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ozon_quantity',
            field=models.IntegerField(default=0, verbose_name='Количество на OZON'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(
                choices=[
                    ('in_stock_warehouse', 'В наличии/Склад'),
                    ('in_stock_ozon', 'В наличии/OZON'),
                    ('sold', 'Продано'),
                ],
                default='in_stock_warehouse',
                max_length=30,
                verbose_name='Статус',
            ),
        ),
        migrations.RunPython(split_stock_statuses, migrations.RunPython.noop),
    ]
