# Generated by Codex on 2026-05-16

from django.db import migrations, models


BLOCKING_STATUS_MARKERS = (
    'validation',
    'blocked',
    'failed',
    'archive',
    'moderation',
    'rejected',
    'not_created',
)


def restore_sellable_status(apps, schema_editor):
    Product = apps.get_model('web', 'Product')
    for product in Product.objects.filter(status='in_stock_ozon', ozon_quantity__gt=0):
        visibility = (product.ozon_visibility or '').lower()
        ozon_status = (product.ozon_status or '').lower()
        if visibility in {'invisible', 'hidden'}:
            continue
        if any(marker in ozon_status for marker in BLOCKING_STATUS_MARKERS):
            continue
        product.status = 'in_sale'
        product.save(update_fields=['status'])


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_product_ozon_quantity_split_stock_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(
                choices=[
                    ('in_stock_warehouse', 'В наличии/Склад'),
                    ('in_stock_ozon', 'В наличии/OZON'),
                    ('in_sale', 'В продаже'),
                    ('sold', 'Продано'),
                ],
                default='in_stock_warehouse',
                max_length=30,
                verbose_name='Статус',
            ),
        ),
        migrations.RunPython(restore_sellable_status, migrations.RunPython.noop),
    ]
