# Generated by Django 6.0.4 on 2026-05-16 15:57

import django.db.models.deletion
from django.db import migrations, models


def seed_batches_and_sale_costs(apps, schema_editor):
    Product = apps.get_model('web', 'Product')
    SaleRecord = apps.get_model('web', 'SaleRecord')
    SupplyBatch = apps.get_model('web', 'SupplyBatch')

    for product in Product.objects.all():
        if product.quantity > 0:
            SupplyBatch.objects.create(
                product=product,
                initial_quantity=product.quantity,
                remaining_quantity=product.quantity,
                cost_remaining_quantity=product.quantity,
                purchase_price=product.purchase_price,
                delivery_cost=product.delivery_cost,
                cost_price=product.cost_price,
            )

    for sale in SaleRecord.objects.select_related('product'):
        if sale.profit is not None and sale.income is not None:
            sale.cost_price = sale.income - sale.profit
        elif sale.product_id:
            sale.cost_price = sale.product.cost_price
        sale.save(update_fields=['cost_price'])


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_restore_in_sale_status_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerecord',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Себестоимость на момент продажи'),
        ),
        migrations.CreateModel(
            name='SupplyBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_quantity', models.IntegerField(default=0, verbose_name='РљРѕР»РёС‡РµСЃС‚РІРѕ РІ РїР°СЂС‚РёРё')),
                ('remaining_quantity', models.IntegerField(default=0, verbose_name='РћСЃС‚Р°С‚РѕРє РїР°СЂС‚РёРё')),
                ('cost_remaining_quantity', models.IntegerField(default=0, verbose_name='Остаток для расчета себестоимости')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Р—Р°РєСѓРїРѕС‡РЅР°СЏ СЃС‚РѕРёРјРѕСЃС‚СЊ')),
                ('delivery_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='РЎС‚РѕРёРјРѕСЃС‚СЊ РґРѕСЃС‚Р°РІРєРё')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='РЎРµР±РµСЃС‚РѕРёРјРѕСЃС‚СЊ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Р”Р°С‚Р° РїРѕСЃС‚Р°РІРєРё')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='web.product', verbose_name='РўРѕРІР°СЂ')),
            ],
            options={
                'verbose_name': 'РџР°СЂС‚РёСЏ РїРѕСЃС‚Р°РІРєРё',
                'verbose_name_plural': 'РџР°СЂС‚РёРё РїРѕСЃС‚Р°РІРѕРє',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddField(
            model_name='salerecord',
            name='supply_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='web.supplybatch', verbose_name='Партия поставки'),
        ),
        migrations.RunPython(seed_batches_and_sale_costs, migrations.RunPython.noop),
    ]
